name: Test

on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: 'test'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: perchunpak
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: perchunpak/statusmc-frontend
        flavor: |
          latest=true

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
